repeat_types:
  week: "Weekly"
  month: "Monthly"
date_format: "%d/%m/%Y"
time_format: "%H:%M"
per_page: 2
user_roles:
  admin: "admin"
  normal: "normal"
number_of_schedules: 8
avatar: [150, 150]
max_avatar_file_size: 5
avatar_extension_white_list: ["jpg", "jpeg", "gif", "png"]
